platform_email_contact: platform_user@soliddistributedsystems.io'
domain_name: 'soliddistributedsystems.io'
platform_dns_hosting: route53
platform_username: platform_username
platform_on_prem: true
platform_name: sds
timezone: 'Europe/Bucharest'
locale: 'C.UTF-8'
vpnsrv_ip: 10.10.80.1
nfs_host: 192.168.100.2
controller_ip: 192.168.100.3
controller_bkp_ip: 192.168.100.4
cp1_ip: 192.168.100.5
cp2_ip: 192.168.100.6
k8s_node1_ip: 192.168.100.7
k8s_node2_ip: 192.168.100.8
k8s_node3_ip: 192.168.100.9
k8s_node4_ip: 192.168.100.10