all:
  hosts:
    vpnsrv:
      ansible_connection: ssh
      ansible_user: "{{ platform_username }}"
      ansible_host: "{{ vpnsrv_ip }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    controller:
      ansible_connection: ssh
      ansible_user: "{{ platform_username }}"
      ansible_host: "{{ controller_ip }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    controller-bkp:
      ansible_connection: ssh
      ansible_user: "{{ platform_username }}"
      ansible_host: "{{ controller_bkp_ip }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    cp1:
      ansible_connection: ssh
      ansible_user: "{{ platform_username }}"
      ansible_host: "{{ cp1_ip }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    cp2:
      ansible_connection: ssh
      ansible_user: "{{ platform_username }}"
      ansible_host: "{{ cp2_ip }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    k8s-node1:
      ansible_connection: ssh
      ansible_user: "{{ platform_username }}"
      ansible_host: "{{ k8s_node1_ip }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    k8s-node2:
      ansible_connection: ssh
      ansible_user: "{{ platform_username }}"
      ansible_host: "{{ k8s_node2_ip }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    k8s-node3:
      ansible_connection: ssh
      ansible_user: "{{ platform_username }}"
      ansible_host: "{{ k8s_node3_ip }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    k8s-node4:
      ansible_connection: ssh
      ansible_user: "{{ platform_username }}"
      ansible_host: "{{ k8s_node4_ip }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'